spring.datasource.url=jdbc:postgresql://dpg-d7kd8a6gvqtc73ap6ug0-a.ohio-postgres.render.com:5432/mintr_db
# postgresql://mintr_db_user:6Nk5LdmArvxg0o73FMsuAJ3KFoWGWmGq@dpg-d7kd8a6gvqtc73ap6ug0-a.ohio-postgres.render.com/mintr_db
spring.datasource.username=mintr_db_user
spring.datasource.password=6Nk5LdmArvxg0o73FMsuAJ3KFoWGWmGq
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}
admin.password=admin12345

# JWT
app.jwtSecret=09a8e74ca03ba9e193401d638e94d5446341f83f023761cdccb4693743e482a0
app.jwtExpirationMs=3600000

# Swagger config
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
